- name: Set up Golang systemd service
  hosts: lekkoatletawka
  become: yes

  vars_files:
  - files/secrets.yml
  vars:
    service_name: "athletics_backend"
    service_description: "Golang Athletics Backend Service"
    service_working_dir: "/var/lib/{{ service_name }}"
    service_bin_dir: "{{ service_working_dir }}/bin"
    service_bin_file: "{{ service_bin_dir }}/{{ service_name }}"

  tasks:
    - name: Ensure required user and group exist
      ansible.builtin.user:
        name: "{{ service_name }}"
        createhome: no
        shell: /usr/sbin/nologin

    - name: Ensure working directory exists
      ansible.builtin.file:
        path: "{{ service_working_dir }}"
        state: directory
        owner: "{{ service_name }}"
        group: "{{ service_name }}"
        mode: '0755'
    
    - name: Ensure binary directory exists
      ansible.builtin.file:
        path: "{{ service_bin_dir }}"
        state: directory
        owner: "{{ service_name }}"
        group: "{{ service_name }}"
        mode: '0755'

    - name: Create systemd service file
      ansible.builtin.template:
        src: files/athletics_backend.j2
        dest: "/etc/systemd/system/{{ service_name }}.service"
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.command: systemctl daemon-reload

    - name: Enable and start the service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        enabled: yes
        state: started
