- name: Configure SSHD
  hosts: lekkoatletawka
  become: yes

  tasks:
    - name: Backup the original sshd_config
      copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.bak
        remote_src: yes

    - name: Copy new sshd_config
      copy:
        src: files/sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: "0644"

    - name: Restart sshd service
      systemd:
        name: ssh
        state: restarted
